### ISSUE TITLE
Not right docs for listeners (copy-paste issue)

### ISSUE THREAD

**Issue by sanya-misharin** [CvekCoding/DomainEvents#1]
https://github.com/CvekCoding/DomainEvents/#listen-on-sync-message
In this section need change comment
_From_:
`if ($event->getLifecycleEvent() === Events::postFlush) {
            // your custom logic on onFlush moment        
}`
_To_:  
`if ($event->getLifecycleEvent() === Events::postFlush) {
            // your custom logic on postFlush moment        
}`

https://github.com/CvekCoding/DomainEvents/#listen-on-async-message
In this section need change comment
_From_:
`if ($event->getLifecycleEvent() === Events::onFlush) {
            // your custom logic on postFlush moment       
}`
_To_:
`if ($event->getLifecycleEvent() === Events::onFlush) {
            // your custom logic on onFlush moment       
}`

**Comment by CvekCoding** [comment]
Done, thanks
